config/routes.rb
Rails.application.routes.draw do
  resources :locals
  #devise_for :users
  root "pages#home"
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/local.rb
class Local < ApplicationRecord
  validates :nome, presence: true
  validates :endereco, presence: true
  validates :religiao_denominacao, presence: true
  validates :descricao, presence: true, length: { minimum: 30, maximum: 65535 }
  validates :eventos, presence: true, length: { minimum: 30, maximum: 65535 }
  validates :contato, presence: true

  geocoded_by :endereco
  after_validation :geocode

  def self.ransackable_attributes(auth_object = nil)
    ["endereco", "religiao_denominacao"]
  end

  RELIGIOES_DENOMINACOES = [
    "Católico",
    "Evangélico",
    "Protestante",
    "Ortodoxo",
    "Anglicano",
    "Luterano",
    "Metodista",
    "Batista",
    "Pentecostal",
    "Adventista",
    "Outro"
  ].freeze
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController
  before_action :set_local, only: %i[ show edit update destroy ]

  # GET /locals or /locals.json
  def index
    @q = Local.ransack(params[:q])
    @locals = @q.result(distinct: true)
   end

  # GET /locals/1 or /locals/1.json
  def show
  end

  # GET /locals/new
  def new
    @local = Local.new
  end

  # GET /locals/1/edit
  def edit
  end

  # POST /locals or /locals.json
  def create
    @local = Local.new(local_params)

    respond_to do |format|
      if @local.save
        format.html { redirect_to local_url(@local), notice: "Local was successfully created." }
        format.json { render :show, status: :created, location: @local }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locals/1 or /locals/1.json
  def update
    respond_to do |format|
      if @local.update(local_params)
        format.html { redirect_to local_url(@local), notice: "Local was successfully updated." }
        format.json { render :show, status: :ok, location: @local }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locals/1 or /locals/1.json
  def destroy
    @local.destroy

    respond_to do |format|
      format.html { redirect_to locals_url, notice: "Local was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local
      @local = Local.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def local_params
      params.require(:local).permit(:nome, :endereco, :religiao_denominacao, :descricao, :eventos, :contato, :latitude, :longitude)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @q = Local.ransack(params[:q])
    end
    
    def about
    end
  
    def contact
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
   end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/views/layouts/_footer.html.erb
<footer class="bg-yellow-200 text-white p-4 mt-auto">
  <div class="container flex justify-between items-center">
    <small>
      <%= link_to 'Grupos de Jovens Cristãos Brasil. Todos os direitos reservados.', root_path, class: 'text-gray-700' %>
    </small>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="bg-yellow-200 p-4">
  <div class="container mx-auto flex justify-between items-center">
    <ul class="flex">
      <li class="mr-6"><%= link_to '✞ Grupos de Jovens Cristãos Brasil', root_path, class: 'text-black font-bold text-lg' %></li>
      <li class="mr-6"><%= link_to 'Sobre', about_path, class: 'text-gray-500 hover:text-black' %></li>
      <li><%= link_to 'Contato', contact_path, class: 'text-gray-500 hover:text-black' %></li>
    </ul>

    <%# <ul class="flex items-center"> %>
    <%#   <li class="mr-6"> %>
    <%#     <% if user_signed_in? %> 
    <%#       <%= link_to 'Sair', destroy_user_session_path, class: 'text-gray-500 hover:text-black' %> 
    <%#     <% else %> 
    <%#       <%= link_to 'Entrar', new_user_registration_path, class: 'text-gray-500 hover:text-black' %> 
    <%#     <% end %> 
    <%#   </li> %>
    <%# </ul> %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HolyPlace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css">
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col min-h-screen bg-gray-100">
    <%= render 'layouts/navbar' %>
    <p class="alert"><%= alert %></p> 
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/locals/_form.html.erb
<%= form_with(model: local, class: "max-w-md mx-auto mt-8") do |form| %>
  <% if local.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold"> <%= pluralize(local.errors.count, "error") %> prohibited this local from being saved:</strong>
      <ul class="mt-3 list-disc list-inside">
        <% local.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :nome, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :nome, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :endereco, "Endereço", class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :endereco, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :religiao_denominacao, "Religião", class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.select :religiao_denominacao, Local::RELIGIOES_DENOMINACOES, {}, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :descricao, "Descrição", class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :descricao, placeholder: "Descreva brevemente o seu grupo.", class: "resize-y h-32 shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :eventos, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :eventos, placeholder: "Cite eventos realizados pelo grupo.", class: "resize-y h-32 shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :contato, "Contato/Redes Sociais", class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :contato, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <%= form.submit "Registrar", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/locals/_local.html.erb
<div id="<%= dom_id local %>" class="bg-gray-100 p-4 shadow-md rounded-md mb-4">
  <div class="container mx-auto mt-5 mb-10 max-w-screen-lg flex">
    <div class="flex-1 mr-8">
      <div>
        <h1 class="text-2xl font-bold text-gray-800 mb-5">
          <%= local.nome %>
        </h1>
      </div>

      <div class="mb-2">
        <p>
          <strong class="text-yellow-800">Endereço</strong><br>
          <%= local.endereco %>
        </p>
      </div>

      <div class="mb-2">
        <p>
          <strong class="text-yellow-800">Religião</strong><br>
          <%= local.religiao_denominacao %>
        </p>
      </div>

     <%= link_to "Abrir no Maps", "https://www.google.com/maps/search/?api=1&query=#{CGI.escape(local.endereco)}", target: "_blank", style: "font-size: 0.875rem; color: #3490dc; text-decoration: none; hover: #2779bd;" %>

     <% if local.latitude.present? && local.longitude.present? %>
      <%= js_map [{latitude: local.latitude, longitude: local.longitude}] %>
     <% end %>
    </div>

    <div class="flex-1">
      <div class="mb-2">
        <p>
          <strong class="text-yellow-800">Descrição</strong><br>
          <%= local.descricao %>
        </p>
      </div>

      <div class="mb-2">
        <p>
          <strong class="text-yellow-800">Eventos</strong><br>
          <%= local.eventos %>
        </p>
      </div>

     <div class="mb-2">
      <p>
        <strong class="text-yellow-800">Contato</strong><br>
        <% if local.contato.present? && local.contato =~ URI::DEFAULT_PARSER.make_regexp %>
          <%= link_to local.contato, local.contato, target: "_blank", class: "text-blue-500 hover:underline" %>
        <% else %>
          <%= local.contato %>
        <% end %>
      </p>
     </div>
    </div>
  </div>
</div>

app/views/locals/_shortlocal.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css">
</head>
<body class="bg-gray-100">
  <div id="<%= dom_id local %>" class="bg-gray-100 p-4 shadow-md rounded-md mb-3">
    <div class="container mx-auto mt-5 mb-10 max-w-screen-lg flex">
      <div class="flex-1 mr-8">
        <div>
          <h1 class="text-2xl font-bold text-gray-800 mb-5">
            <%= local.nome %>
          </h1>
        </div>

        <div class="mb-2">
          <p>
            <strong class="text-yellow-800">Endereço</strong><br>
            <%= local.endereco %>
          </p>
        </div>

        <div class="mb-2">
          <p>
            <strong class="text-yellow-800">Religião</strong><br>
            <%= local.religiao_denominacao %>
          </p>
        </div>

      <%= link_to "Abrir no Maps", "https://www.google.com/maps/search/?api=1&query=#{CGI.escape(local.endereco)}", target: "_blank", style: "font-size: 0.875rem; color: #3490dc; text-decoration: none; hover: #2779bd;" %>
      </div>

      <div class="flex-1">
        <div class="mb-2">
          <p>
            <strong class="text-yellow-800">Descrição</strong><br>
            <%= truncate(local.descricao, length: 200, separator: ' ', omission: '...') %>
          </p>
        </div>

        <div class="mb-2">
          <p>
            <strong class="text-yellow-800">Eventos</strong><br>
            <%= truncate(local.eventos, length: 200, separator: ' ', omission: '...') %>
          </p>
        </div>

        <div class="mt-4">
          <%= link_to "Ver detalhes", local, class: "text-blue-500 hover:text-blue-700" %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/locals/edit.html.erb
<h1>Editing local</h1>

<%= render "form", local: @local %>

<br>

<div class="text-center">
  <%= link_to "Ver todos os grupos", locals_path, class: "text-blue-500 hover:underline" %>
</div>

app/views/locals/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css">
</head>
<body class="bg-gray-100">
  <p style="color: green"><%= notice %></p>

  <div class="container mx-auto mt-7 max-w-screen-lg">
    <!-- Search Container -->
    <div class="mb-4">
      <%= search_form_for @q do |f| %>

      <div class="flex items-center mb-2">
        <%= f.label :endereco_cont, "Buscar", class: 'mr-2' %>
        <%= f.search_field :endereco_cont, placeholder: 'Ex: Cidade, Estado e rua ', class: 'p-2 border rounded mr-2 w-full' %>
        <%= f.label :religiao_denominacao_eq, "Religião", class: 'mr-2' %>
        <%= f.select :religiao_denominacao_eq, Local::RELIGIOES_DENOMINACOES, { include_blank: true }, class: 'p-2 border rounded w-96' %>

        <%= f.submit 'Buscar', class: 'p-2 bg-blue-500 hover:bg-blue-700 text-white rounded md:ml-2 w-1/6' %>
      </div>
      <% end %>
    </div>
  </div>

  <div id="locals">
    <% @locals.each do |local| %>
      <%= render partial: 'shortlocal', locals: { local: local } %>
    <% end %>
  </div>
</body>

app/views/locals/new.html.erb
<%= render "form", local: @local %>

<br>

<div style="text-align: center;">
  <%= link_to "Ver todos os grupos", locals_path, style: "color: #3498db;" %>
</div>

app/views/locals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @local %>

<div class="flex items-center space-x-4 mb-4">
<%# <% if user_signed_in? %> %>
  <%#   <%= link_to "Editar este grupo", edit_local_path(@local), class: "text-yellow-800 hover:text-yellow-600" %>
  <%#   <%= button_to "Excluir este grupo", @local, method: :delete, data: { confirm: "Tem certeza?" }, class: "text-yellow-800 hover:text-yellow-600" %>
  <%# <% end %> 
  <%= link_to "Ver todos os grupos", locals_path, class: "text-yellow-800 hover:text-yellow-600" %>
</div>

app/views/pages/about.html.erb
<% content_for :body_class, 'body' %>

<div class="max-w-2xl mx-auto my-8 p-6 bg-white rounded-lg shadow-md">
  <h1 class="text-3xl font-bold mb-4">Sobre</h1>

  <p class="text-gray-700">
    Bem-vindo ao Grupos de Jovens Cristãos Brasil! <br>
    <br>
    Somos uma plataforma dedicada a conectar jovens cristãos em todo o Brasil, proporcionando um espaço virtual para pesquisa e registro de grupos de jovens. Se você está em busca de comunidades cristãs vibrantes e inspiradoras em sua região, você está no lugar certo.
    <br>
    <br>
    Navegue por nossa plataforma para descobrir grupos de jovens cristãos próximos a você. Encontre encontros semanais, eventos especiais e oportunidades para se envolver em atividades que fortalecem a fé e promovem a comunhão entre os jovens que compartilham valores cristãos.
    <br>
    <br>
    Se você lidera ou participa de um grupo de jovens, aproveite para registrar seu grupo conosco. Dessa forma, você estará contribuindo para a expansão dessa rede de comunidades que buscam viver a fé de maneira autêntica e relevante.
    <br>
    <br>
    Junte-se a nós no Grupos de Jovens Cristãos Brasil, onde a comunhão, a amizade e o crescimento espiritual se encontram!
  </p>
</div>

app/views/pages/contact.html.erb
<% content_for :body_class, 'body' %>

<div class="max-w-2xl mx-auto my-8 p-6 bg-white rounded-lg shadow-md">
  <h1 class="text-3xl font-bold mb-4">Contato</h1>

  <p class="text-gray-700">
    Construído por João Gabriel Dal Forno utilizando Ruby on Rails.
    <br>
    <br>
    Entre em contato por: 
    <br>
    <a href="https://www.linkedin.com/in/joaogabrieldf/" class="text-blue-500 hover:underline">Linkedin</a>
    <br>
    <a href="joao.dal@acad.ufsm.br" class="text-blue-500 hover:underline">Email</a>
  </p>
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css">
  <style>
    /* Adicione estilos personalizados aqui, se necessário */
  </style>
</head>
<body class="bg-gray-100">

  <div class="container mx-auto mt-10 mb-10 max-w-screen-lg">
    <!-- Search Container -->
    <div class="mb-8">
      <%= search_form_for @q do |f| %>
      <div class="flex flex-col md:flex-row items-center mb-4">
        <%= f.label :endereco_cont, "Buscar", class: 'mr-2' %>
        <%= f.search_field :endereco_cont, placeholder: 'Ex: Cidade, Estado e rua', class: 'p-2 border rounded mb-2 md:mb-0 md:mr-2 w-full md:w-1/2' %>
        <%= f.label :religiao_denominacao_eq, "Religião", class: 'mr-2' %>
        <%= f.select :religiao_denominacao_eq, Local::RELIGIOES_DENOMINACOES, { include_blank: true }, class: 'p-2 border rounded mb-2 md:mb-0 w-full md:w-1/4' %>
        <%= f.submit 'Buscar', class: 'p-2 bg-blue-500 hover:bg-blue-700 text-white rounded md:ml-2 w-1/6' %>
      </div>
      <% end %>
    </div>

    <div class="bg-white p-8 rounded-lg shadow-lg">
      <h1 class="text-4xl font-bold mb-4">Grupos de Jovens Cristãos Brasil</h1>
      <p class="mb-4 text-gray-700">
        Seja bem-vindo! Este portal foi pensado para te ajudar a encontrar grupos de jovens cristãos perto de você! Faça sua busca nos campos acima. <br> 
        <br>
        Já faz parte de um grupo de jovens? Registre seu grupo abaixo:
      </p>
      <div class="flex justify-left">
        <%= link_to 'Registrar novo grupo', 'locals/new', class: 'p-2 bg-gray-300 text-gray-700 rounded hover:bg-gray-400 transition duration-300' %>
      </div>
      <img src="<%= asset_path('home_thumb.jpg') %>" alt="Descrição da imagem" class="mt-4 mx-auto w-1/2">
        <p class="mb-4 text-gray-800 italic">
          <br>
            Atualmente temos <%= Local.count %> grupos cadastrados.
        </p>
    </div>
  </div>
</body>
</html>